name: flyodide
description: "A Flutter wrapper around Pyodide to execute Python in a Flutter app."
version: 0.0.1
homepage: https://github.com/Shahxad-Akram/flyodide

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_plus: ^0.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - packages/flyodide/core/index.html
    - packages/flyodide/core/main.js
    - packages/flyodide/core/pyodide/package.json
    - packages/flyodide/core/pyodide/pyodide.asm.js
    - packages/flyodide/core/pyodide/pyodide.asm.wasm
    - packages/flyodide/core/pyodide/pyodide-lock.json
    - packages/flyodide/core/pyodide/python_stdlib.zip